"""
PLAN_TASK Tool - Callable tool for planning

This file is auto-generated by ToolsGenerator.
Agents can discover this tool by reading the filesystem and import it directly.

To use this tool:
    from athena.tools.planning.plan_task import plan_task
    result = plan_task(...)
"""


# This tool is auto-generated by ToolsGenerator
# Agents should use the manager directly instead of calling this stub
# See: athena.manager.UnifiedMemoryManager.plan_task()

def plan_task(description: str, depth: int = 3):
    """
Decompose a task into an executable plan

Parameters:
    description: Task description
    depth: Planning depth

Returns:
    Plan - Hierarchical task plan

Example:
    >>> plan_task('Implement user authentication')
"""

    # To use this tool properly:
    # 1. Import from the manager: from athena.manager import UnifiedMemoryManager
    # 2. Create an instance: manager = UnifiedMemoryManager()
    # 3. Call the method: result = manager.plan_task(description, depth)
    #
    # OR import the MCP tools directly:
    # from athena.mcp.tools import plan_task

    raise NotImplementedError(
        "Use manager directly: from athena.manager import UnifiedMemoryManager\n"
        "Or import MCP tools: from athena.mcp.tools import plan_task"
    )

