"""
VALIDATE_PLAN Tool - Callable tool for planning

This file is auto-generated by ToolsGenerator.
Agents can discover this tool by reading the filesystem and import it directly.

To use this tool:
    from athena.tools.planning.validate_plan import validate_plan
    result = validate_plan(...)
"""


# This tool is auto-generated by ToolsGenerator
# Agents should use the manager directly instead of calling this stub
# See: athena.manager.UnifiedMemoryManager.validate_plan()

def validate_plan(plan: Plan, scenarios: int = 5):
    """
Validate a plan using formal verification and scenario testing

Parameters:
    plan: Plan to validate
    scenarios: Number of scenarios

Returns:
    ValidationResult - Plan validity and issues

Example:
    >>> validate_plan(my_plan)
"""

    # To use this tool properly:
    # 1. Import from the manager: from athena.manager import UnifiedMemoryManager
    # 2. Create an instance: manager = UnifiedMemoryManager()
    # 3. Call the method: result = manager.validate_plan(plan, scenarios)
    #
    # OR import the MCP tools directly:
    # from athena.mcp.tools import validate_plan

    raise NotImplementedError(
        "Use manager directly: from athena.manager import UnifiedMemoryManager\n"
        "Or import MCP tools: from athena.mcp.tools import validate_plan"
    )

