"""
CONSOLIDATE Tool - Callable tool for consolidation

This file is auto-generated by ToolsGenerator.
Agents can discover this tool by reading the filesystem and import it directly.

To use this tool:
    from athena.tools.consolidation.consolidate import consolidate
    result = consolidate(...)
"""


# This tool is auto-generated by ToolsGenerator
# Agents should use the manager directly instead of calling this stub
# See: athena.manager.UnifiedMemoryManager.consolidate()

def consolidate(strategy: str = balanced, days_back: int = 7):
    """
Extract patterns from episodic events (sleep-like consolidation)

Parameters:
    strategy: Strategy: balanced/speed/quality
    days_back: Days of events to consolidate

Returns:
    ConsolidationReport - Patterns extracted and quality metrics

Example:
    >>> consolidate(strategy='quality')
"""

    # To use this tool properly:
    # 1. Import from the manager: from athena.manager import UnifiedMemoryManager
    # 2. Create an instance: manager = UnifiedMemoryManager()
    # 3. Call the method: result = manager.consolidate(strategy, days_back)
    #
    # OR import the MCP tools directly:
    # from athena.mcp.tools import consolidate

    raise NotImplementedError(
        "Use manager directly: from athena.manager import UnifiedMemoryManager\n"
        "Or import MCP tools: from athena.mcp.tools import consolidate"
    )

