"""
GET_PATTERNS Tool - Callable tool for consolidation

This file is auto-generated by ToolsGenerator.
Agents can discover this tool by reading the filesystem and import it directly.

To use this tool:
    from athena.tools.consolidation.get_patterns import get_patterns
    result = get_patterns(...)
"""


# This tool is auto-generated by ToolsGenerator
# Agents should use the manager directly instead of calling this stub
# See: athena.manager.UnifiedMemoryManager.get_patterns()

def get_patterns(domain: str, limit: int = 10):
    """
Retrieve learned patterns from consolidation

Parameters:
    domain: Optional domain filter
    limit: Max patterns

Returns:
    List[Pattern] - Learned patterns with confidence scores

Example:
    >>> get_patterns(domain='security', limit=5)
"""

    # To use this tool properly:
    # 1. Import from the manager: from athena.manager import UnifiedMemoryManager
    # 2. Create an instance: manager = UnifiedMemoryManager()
    # 3. Call the method: result = manager.get_patterns(domain, limit)
    #
    # OR import the MCP tools directly:
    # from athena.mcp.tools import get_patterns

    raise NotImplementedError(
        "Use manager directly: from athena.manager import UnifiedMemoryManager\n"
        "Or import MCP tools: from athena.mcp.tools import get_patterns"
    )

