"""
FORGET Tool - Callable tool for memory

This file is auto-generated by ToolsGenerator.
Agents can discover this tool by reading the filesystem and import it directly.

To use this tool:
    from athena.tools.memory.forget import forget
    result = forget(...)
"""


# This tool is auto-generated by ToolsGenerator
# Agents should use the manager directly instead of calling this stub
# See: athena.manager.UnifiedMemoryManager.forget()

def forget(memory_id: str):
    """
Delete a memory by ID

Parameters:
    memory_id: ID of memory to delete

Returns:
    bool - True if deleted

Example:
    >>> forget('mem_12345')
"""

    # To use this tool properly:
    # 1. Import from the manager: from athena.manager import UnifiedMemoryManager
    # 2. Create an instance: manager = UnifiedMemoryManager()
    # 3. Call the method: result = manager.forget(memory_id)
    #
    # OR import the MCP tools directly:
    # from athena.mcp.tools import forget

    raise NotImplementedError(
        "Use manager directly: from athena.manager import UnifiedMemoryManager\n"
        "Or import MCP tools: from athena.mcp.tools import forget"
    )

