"""
REMEMBER Tool - Callable tool for memory

This file is auto-generated by ToolsGenerator.
Agents can discover this tool by reading the filesystem and import it directly.

To use this tool:
    from athena.tools.memory.remember import remember
    result = remember(...)
"""


# This tool is auto-generated by ToolsGenerator
# Agents should use the manager directly instead of calling this stub
# See: athena.manager.UnifiedMemoryManager.remember()

def remember(content: str, event_type: str = action, tags: List[str] = []):
    """
Record a new episodic event or semantic memory

Parameters:
    content: Memory content
    event_type: Type of event
    tags: Optional tags

Returns:
    str - Memory ID

Example:
    >>> remember('Implemented user auth', tags=['security', 'auth'])
"""

    # To use this tool properly:
    # 1. Import from the manager: from athena.manager import UnifiedMemoryManager
    # 2. Create an instance: manager = UnifiedMemoryManager()
    # 3. Call the method: result = manager.remember(content, event_type, tags)
    #
    # OR import the MCP tools directly:
    # from athena.mcp.tools import remember

    raise NotImplementedError(
        "Use manager directly: from athena.manager import UnifiedMemoryManager\n"
        "Or import MCP tools: from athena.mcp.tools import remember"
    )

