export { useAPI } from './useAPI'
export { useLocalStorage } from './useLocalStorage'
export { useDebounce } from './useDebounce'
export { useWebSocket } from './useWebSocket'
export { useRealtimeData } from './useRealtimeData'
export { useAdvancedSearch, useSearchSuggestions, highlightMatches, type SearchFilter, type SearchResult, type SearchResponse } from './useAdvancedSearch'
